CREATE TABLE EMPLEADO (
    ID int not null unique,
    Contraseña varchar(255),
    Email varchar(255)
);
ALTER TABLE EMPLEADO ADD CONSTRAINT PK_EMPLEADO PRIMARY KEY(ID);

CREATE TABLE DEPARTAMENTO (
    ID int not null unique,
    Nombre varchar(256)
);
ALTER TABLE DEPARTAMENTO ADD CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY(ID);

CREATE TABLE ACTIVO (
    ID int not null unique,
    Nombre varchar(64),
    Descripcion varchar(512),
    ID_Departamento int,
    NFS int
);
ALTER TABLE ACTIVO ADD CONSTRAINT PK_ACTIVO PRIMARY KEY(ID);
ALTER TABLE ACTIVO ADD CONSTRAINT FK_ACTIVO_DEPARTAMENTO FOREIGN KEY (ID_Departamento) REFERENCES DEPARTAMENTO(ID);

CREATE TABLE REGISTRO_DE_ACTIVOS (
    ID_Empleado int not null,
    ID_Activo int not null,
    Fecha DATETIME,
    Periodo varchar(255)
);
ALTER TABLE REGISTRO_DE_ACTIVOS ADD CONSTRAINT PK_REGISTRO_DE_ACTIVOS PRIMARY KEY(ID_Empleado, ID_Activo);
ALTER TABLE REGISTRO_DE_ACTIVOS ADD CONSTRAINT FK_REGISTRO_DE_ACTIVOS_EMPLEADO FOREIGN KEY (ID_Empleado) REFERENCES EMPLEADO(ID);
ALTER TABLE REGISTRO_DE_ACTIVOS ADD CONSTRAINT FK_REGISTRO_DE_ACTIVOS_ACTIVOS FOREIGN KEY (ID_Activo) REFERENCES Activo(ID);

CREATE TABLE EMPLEADO_EN_DEPARTAMENTO (
    ID_Departamento int not null,
    ID_Empleado int not null
);
ALTER TABLE EMPLEADO_EN_DEPARTAMENTO ADD CONSTRAINT PK_REGISTRO_DE_ACTIVOS PRIMARY KEY(ID_Departamento, ID_Empleado);
ALTER TABLE EMPLEADO_EN_DEPARTAMENTO ADD CONSTRAINT FK_REGISTRO_DE_ACTIVOS_EMPLEADO FOREIGN KEY (ID_Empleado) REFERENCES EMPLEADO(ID);
ALTER TABLE EMPLEADO_EN_DEPARTAMENTO ADD CONSTRAINT FK_REGISTRO_DE_ACTIVOS_DEPARTAMENTO FOREIGN KEY (ID_Departamento) REFERENCES DEPARTAMENTO(ID);