-- Drop foreign key constraints from ITEM_REGISTRY table (if they exist)
IF EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_ITEM_REGISTRY_EMPLOYEE')
    ALTER TABLE ITEM_REGISTRY DROP CONSTRAINT FK_ITEM_REGISTRY_EMPLOYEE;

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_ITEM_REGISTRY_ITEM')
    ALTER TABLE ITEM_REGISTRY DROP CONSTRAINT FK_ITEM_REGISTRY_ITEM;

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_ITEM_REGISTRY_ROOM')
    ALTER TABLE ITEM_REGISTRY DROP CONSTRAINT FK_ITEM_REGISTRY_ROOM;

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_ITEM_REGISTRY_CYCLE')
    ALTER TABLE ITEM_REGISTRY DROP CONSTRAINT FK_ITEM_REGISTRY_CYCLE;

-- Drop foreign key constraints from ITEM table
IF EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_ITEM_DEPARTMENT')
    ALTER TABLE ITEM DROP CONSTRAINT FK_ITEM_DEPARTMENT;

-- Drop foreign key constraints from EMPLOYEE table
IF EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_EMPLOYEE_DEPARTMENT')
    ALTER TABLE EMPLOYEE DROP CONSTRAINT FK_EMPLOYEE_DEPARTMENT;

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_EMPLOYEE_ROLE')
    ALTER TABLE EMPLOYEE DROP CONSTRAINT FK_EMPLOYEE_ROLE;

-- Drop foreign key constraints from ROOM table
IF EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_ROOM_DEPARTMENT')
    ALTER TABLE ROOM DROP CONSTRAINT FK_ROOM_DEPARTMENT;

-- Drop the ITEM_REGISTRY table
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'ITEM_REGISTRY') AND type = N'U')
    DROP TABLE ITEM_REGISTRY;

-- Drop the ROOM table
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'ROOM') AND type = N'U')
    DROP TABLE ROOM;

-- Drop the ITEM table
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'ITEM') AND type = N'U')
    DROP TABLE ITEM;

-- Drop the EMPLOYEE table
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'EMPLOYEE') AND type = N'U')
    DROP TABLE EMPLOYEE;

-- Drop the DEPARTMENT table
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'DEPARTMENT') AND type = N'U')
    DROP TABLE DEPARTMENT;

-- Drop the ROLE table
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'ROLE') AND type = N'U')
    DROP TABLE ROLE;

-- Drop the CYCLE table
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'CYCLE') AND type = N'U')
    DROP TABLE CYCLE;